<a href="https://colab.research.google.com/github/soueuwilliam/Estudos-IA/blob/main/Universo_Discreto/Machine_Learning/ML02_Vari%C3%A1veis_Categ%C3%B3ricas_e_Separa%C3%A7%C3%A3o_em_Teste_e_Treino.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# importando bibliotecas

In [23]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer

# Baixando base de dados e preenchendendo dados faltantes

In [29]:
baseDeDados = pd.read_csv('https://raw.githubusercontent.com/lucaslattari/MachineLearningSeries/master/Ep%202/admission.csv',delimiter=';')
x = baseDeDados.iloc[:,:-1].values
y = baseDeDados.iloc[:,-1].values

imputer = SimpleImputer(missing_values=np.nan, strategy='median')
imputer = imputer.fit_transform(x[:,1:])

## Label Enconder

In [30]:
from sklearn.preprocessing import LabelEncoder

labelenconder_x = LabelEncoder()
x[:, 0] = labelenconder_x.fit_transform(x[:, 0])
print(x)

[[6 337 118 4 4.5 4.5 9.65 1]
 [0 324 107 4 4.0 4.5 8.87 1]
 [5 316 104 3 3.0 3.5 8.0 1]
 [1 322 110 3 3.5 2.5 8.67 1]
 [8 314 103 2 2.0 3.0 8.21 0]
 [4 330 115 5 4.5 3.0 9.34 1]
 [3 321 109 3 3.0 4.0 8.2 1]
 [2 308 101 2 3.0 4.0 7.9 0]
 [7 302 102 1 2.0 1.5 8.0 0]]


##One hot Encoding

In [31]:
x = x[:, 1:]
d = pd.get_dummies(x[:,0])
x = np.insert(x, 0, d.values, axis=1)
print(x)

[[False False False False False False False False True 337 118 4 4.5 4.5
  9.65 1]
 [False False False False False False False True False 324 107 4 4.0 4.5
  8.87 1]
 [False False False False True False False False False 316 104 3 3.0 3.5
  8.0 1]
 [False False True False False False False False False 322 110 3 3.5 2.5
  8.67 1]
 [False False False False False False True False False 314 103 2 2.0 3.0
  8.21 0]
 [False False False True False False False False False 330 115 5 4.5 3.0
  9.34 1]
 [False True False False False False False False False 321 109 3 3.0 4.0
  8.2 1]
 [False False False False False True False False False 308 101 2 3.0 4.0
  7.9 0]
 [True False False False False False False False False 302 102 1 2.0 1.5
  8.0 0]]


## Separando Treino e Teste

In [32]:
from sklearn.model_selection import  train_test_split

xTrain, xTest, yTrain, yTest = train_test_split(x , y, test_size = 0.2)


[[False False False False False False True False False 314 103 2 2.0 3.0
  8.21 0]
 [False False False False False True False False False 308 101 2 3.0 4.0
  7.9 0]
 [False True False False False False False False False 321 109 3 3.0 4.0
  8.2 1]
 [False False False False False False False True False 324 107 4 4.0 4.5
  8.87 1]
 [True False False False False False False False False 302 102 1 2.0 1.5
  8.0 0]
 [False False False False True False False False False 316 104 3 3.0 3.5
  8.0 1]
 [False False True False False False False False False 322 110 3 3.5 2.5
  8.67 1]]
